In [1]:
import numpy as np

In [2]:
lista=[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr=np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[1,2]


6

In [15]:

arr 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[0:3]

array([1, 2, 3])

In [17]:
arr[0:4]

array([1, 2, 3, 4])