In [12]:
import numpy as np 

In [2]:
lista=[1,2,3,4,5]


In [3]:
lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
arr=np.arange(0,10)
arr2=np.copy(arr)

arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr2*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
11/arr2

/var/folders/nm/s2dmh8jn00g2cc_g71smmqc00000gn/T/ipykernel_22953/2069445286.py:1: RuntimeWarning: divide by zero encountered in true_divide
  11/arr2


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

In [19]:
matriz=arr.reshape(2,5)

In [20]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
matriz2=matriz.copy()

In [22]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [25]:
matriz2=matriz2*2

In [26]:
matriz


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [28]:
matriz +matriz2

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [29]:
matriz*matriz2

array([[  0,   2,   8,  18,  32],
       [ 50,  72,  98, 128, 162]])

In [30]:
matriz2-matriz


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
np.matmul(matriz,matriz2.T)

array([[ 60, 160],
       [160, 510]])

In [34]:
matriz@matriz2.T

array([[ 60, 160],
       [160, 510]])