In [4]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr=np.array(arr)

In [13]:
arr=np.array(arr,dtype="float64")


In [14]:
arr.dtype


dtype('float64')

In [15]:
arr

array([1., 2., 3., 4.])

In [16]:
arr=[0,1,2,3,4,5,6]

In [17]:
arr=np.array(arr)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
arr.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6.])

In [23]:
arr.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S21')