In [2]:
import numpy as np

In [5]:
scalar=np.array(42)
print(scalar)
scalar.ndim

42


0

In [6]:
vector=np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [10]:
vector=np.array([[1,2,3],[4,5,6]])
print(vector)
vector.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
tensor=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(vector)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [12]:
vector=np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [22]:
expand=np.expand_dims(np.array([1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17]),axis=0)
print(expand)
expand.ndim

[[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17]]


2

In [39]:
arr=np.array([[1,2,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]])
print(arr)
print("-----------------------------------")
expand=np.expand_dims(np.array([[1,2,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]]),axis=0)
print(expand)
expand.ndim

[[ 1  2  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
-----------------------------------
[[[ 1  2  4  5]
  [ 6  7  8  9]
  [10 11 12 13]
  [14 15 16 17]]]


3

In [41]:
expand=np.expand_dims(np.array([[1,2,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]]),axis=1)
print(expand)
expand.ndim

[[[ 1  2  4  5]]

 [[ 6  7  8  9]]

 [[10 11 12 13]]

 [[14 15 16 17]]]


3

In [42]:
expand=np.expand_dims(np.array([[1,2,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]]),axis=2)
print(expand)
expand.ndim

[[[ 1]
  [ 2]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]]

 [[14]
  [15]
  [16]
  [17]]]


3

In [18]:
print(vector,vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
