In [5]:
import numpy as np


In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((10,15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand()

0.705730746881419

In [25]:
np.random.rand(4)

array([0.34245914, 0.53513052, 0.07581725, 0.98479021])

In [27]:
np.random.rand(4,4)

array([[0.01106003, 0.96230979, 0.72680566, 0.84936141],
       [0.36601344, 0.90342435, 0.04831233, 0.00651366],
       [0.88427302, 0.60088865, 0.10554552, 0.23974031],
       [0.92104427, 0.72686126, 0.02286798, 0.09843015]])

In [28]:
np.random.randint(1,100,(10,10))

array([[41, 98, 36, 33, 80, 78, 19, 85, 42, 33],
       [28, 82, 83, 78, 14, 65, 23, 71, 34,  7],
       [62, 76, 89, 44, 48, 28, 48, 31, 14, 83],
       [98, 71, 50, 58, 64, 24, 53, 87,  2, 98],
       [64, 65, 46, 44, 58, 67, 46, 21, 46, 88],
       [90, 35,  3, 97, 91, 24, 40, 71, 84, 55],
       [75, 67, 50, 65, 95, 39, 97, 70, 97, 32],
       [98, 73, 62, 49, 77, 16, 25, 88, 44, 13],
       [19, 25, 72, 24, 18, 98, 15, 51, 56, 60],
       [ 3, 35, 86, 27, 19, 45, 10,  8, 15, 62]])