In [1]:
import numpy as np

In [6]:
arr=np.random.randint(1,10,(13,10))
arr

array([[1, 8, 1, 9, 9, 2, 3, 5, 5, 3],
       [5, 4, 5, 9, 1, 3, 5, 6, 7, 6],
       [2, 1, 1, 7, 6, 5, 5, 5, 1, 5],
       [3, 2, 4, 2, 2, 6, 7, 4, 7, 3],
       [5, 7, 5, 8, 6, 4, 4, 3, 4, 6],
       [9, 8, 5, 6, 5, 3, 7, 3, 5, 9],
       [6, 2, 4, 9, 6, 4, 2, 5, 4, 6],
       [7, 2, 5, 8, 6, 3, 4, 3, 2, 1],
       [7, 2, 5, 4, 3, 6, 3, 3, 3, 7],
       [4, 9, 4, 8, 2, 2, 4, 1, 2, 2],
       [2, 1, 1, 1, 1, 6, 4, 2, 4, 7],
       [9, 7, 6, 4, 3, 4, 1, 5, 3, 8],
       [7, 1, 6, 1, 3, 3, 4, 2, 9, 4]])

In [7]:
arr.shape

(13, 10)

In [9]:
arr.reshape(10,13)

array([[1, 8, 1, 9, 9, 2, 3, 5, 5, 3, 5, 4, 5],
       [9, 1, 3, 5, 6, 7, 6, 2, 1, 1, 7, 6, 5],
       [5, 5, 1, 5, 3, 2, 4, 2, 2, 6, 7, 4, 7],
       [3, 5, 7, 5, 8, 6, 4, 4, 3, 4, 6, 9, 8],
       [5, 6, 5, 3, 7, 3, 5, 9, 6, 2, 4, 9, 6],
       [4, 2, 5, 4, 6, 7, 2, 5, 8, 6, 3, 4, 3],
       [2, 1, 7, 2, 5, 4, 3, 6, 3, 3, 3, 7, 4],
       [9, 4, 8, 2, 2, 4, 1, 2, 2, 2, 1, 1, 1],
       [1, 6, 4, 2, 4, 7, 9, 7, 6, 4, 3, 4, 1],
       [5, 3, 8, 7, 1, 6, 1, 3, 3, 4, 2, 9, 4]])

In [12]:
arr2=np.random.randint(1,10,(4,3))
arr2

array([[8, 6, 9],
       [8, 5, 9],
       [9, 6, 6],
       [4, 8, 8]])

In [13]:
arr2.reshape(3,4)

array([[8, 6, 9, 8],
       [5, 9, 9, 6],
       [6, 4, 8, 8]])

In [14]:
np.reshape(arr2,(4,3))

array([[8, 6, 9],
       [8, 5, 9],
       [9, 6, 6],
       [4, 8, 8]])

In [15]:
np.reshape(arr2,(4,3),"c")

array([[8, 6, 9],
       [8, 5, 9],
       [9, 6, 6],
       [4, 8, 8]])

In [16]:
np.reshape(arr2,(4,3),"f")

array([[8, 6, 9],
       [8, 5, 9],
       [9, 6, 6],
       [4, 8, 8]])

In [17]:
np.reshape(arr2,(4,3),"a")

array([[8, 6, 9],
       [8, 5, 9],
       [9, 6, 6],
       [4, 8, 8]])

In [18]:
arr2

array([[8, 6, 9],
       [8, 5, 9],
       [9, 6, 6],
       [4, 8, 8]])

In [19]:
np.reshape(arr2,(3,4),"c")

array([[8, 6, 9, 8],
       [5, 9, 9, 6],
       [6, 4, 8, 8]])