In [1]:
import numpy as np

In [5]:
arr=np.random.randint(1,20,10)
arr

array([13, 17, 18, 19, 11,  6,  3, 11,  4, 15])

In [6]:
matriz=np.reshape(arr,(2,5))
matriz

array([[13, 17, 18, 19, 11],
       [ 6,  3, 11,  4, 15]])

In [7]:
arr.max()

19

In [8]:
matriz.max(1)

19

In [9]:
matriz.max(0)

array([13, 17, 18, 19, 15])

In [10]:
matriz.max(1)

array([19, 15])

In [11]:
arr

array([13, 17, 18, 19, 11,  6,  3, 11,  4, 15])

In [12]:
arr.argmax()

3

In [13]:
matriz.argmax(1)

array([3, 4])

In [14]:
arr

array([13, 17, 18, 19, 11,  6,  3, 11,  4, 15])

In [15]:
matriz

array([[13, 17, 18, 19, 11],
       [ 6,  3, 11,  4, 15]])

In [16]:
arr.ptp()

16

In [17]:
matriz.ptp(0)

array([ 7, 14,  7, 15,  4])

In [18]:
np.percentile(arr,50)

12.0

In [19]:
arr

array([13, 17, 18, 19, 11,  6,  3, 11,  4, 15])

In [23]:
arr.sort()
arr

array([ 3,  4,  6, 11, 11, 13, 15, 17, 18, 19])

In [24]:
np.median(arr)

12.0

In [25]:
matriz

array([[ 3,  4,  6, 11, 11],
       [13, 15, 17, 18, 19]])

In [26]:
np.median(matriz,1)

array([ 6., 17.])

In [30]:
np.std(arr)

5.496362433464518

In [28]:
np.var(arr)

30.209999999999997

In [31]:
arr

array([ 3,  4,  6, 11, 11, 13, 15, 17, 18, 19])

In [32]:
np.mean(arr)

11.7

In [33]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
b=np.array([5,6])
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [36]:
a.ndim

2

In [39]:
b.ndim

2

In [40]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])