In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
matriz=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [4]:
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
matriz[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
trozo_de_arr=arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
trozo_de_arr[:]=0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [15]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
casa=arr[:]
casa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
casa[:3]=0
casa

array([ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr

array([ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy=arr.copy()

In [24]:
arr_copy[:]=100

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])